# game settings
WIDTH = 600
HEIGHT = 800
FPS = 60

# colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)

# player data
PLAYER_START_X = WIDTH / 2
PLAYER_START_Y = HEIGHT - 50
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 35
PLAYER_SPEED = 10
PLAYER_HP = 5

# enemy data
REGULAR_ENEMY_WIDTH = 50
REGULAR_ENEMY_HEIGHT = 50
MOVING_ENEMY_SPEED = 2
REGULAR_ENEMY_HP = 1
MOVING_ENEMY_HP = 3

# player bullet data
PLAYER_BULLET_WIDTH = 10
PLAYER_BULLET_HEIGHT = 25
PLAYER_BULLET_SPEED = 12
PLAYER_BULLET_DMG = 1

# enemy bullet data
ENEMY_BULLET_SPEED = 6
ENEMY_BULLET_DAMAGE = 1
ENEMY_BULLET_WIDTH = 10
ENEMY_BULLET_HEIGHT = 25

# powerup data
POWERUP_SPEED = 5

# HUD data
BAR_LENGTH = 100
BAR_HEIGHT = 10

# file data
PLAYER_IMG = "player_ship.png"
PLAYER_BULLET_IMG = "laser_blue.png"
REGULAR_ENEMY_IMG = "enemy_ship.png"
ENEMY_BULLET_IMG = "laser_green.png"